name: Flutter CI with Jira Integration

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Configurar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'

      # 3) Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4) Analizar código
      - name: Run analyzer
        run: flutter analyze

      # 5) Correr tests
      - name: Run tests
        run: flutter test

